### ISSUE TITLE
Make Firefox profile for selenium

### ISSUE THREAD

**Issue by BrongoObenge** [ProjectCalla/SomeCrawler#4]
add in the profile 
`user_pref("browser.cache.disk.enable", false);`
`user_pref("browser.cache.memory.enable", false);`
`user_pref("browser.cache.offline.enable", false);`
`user_pref("network.http.use-cache", false);`

use this:
`profile = webdriver.FirefoxProfile()`
`profile.set_preference('browser.download.folderList', 2)`
`profile.set_preference('browser.download.manager.showWhenStarting', False)`
`profile.set_preference('browser.download.dir', os.getcwd())`
`profile.set_preference('browser.helperApps.neverAsk.saveToDisk', 'text/csv/xls')`
`driver = webdriver.Firefox(profile)`

**Comment by BernardoGO** [comment]
@Jiar 
It is throwing an error.

**Comment by Sharpe23** [comment]
@BernardoGO 
you should update the driver for the new firefox
